version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: spring-angular-template/backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ..
      dockerfile: spring-angular-template/frontend/Dockerfile
    container_name: frontend
    ports:
      - "4200:80"