name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FRONTEND_FLY_APP: ${{ secrets.FRONTEND_FLY_APP }}
      BACKEND_FLY_APP: ${{ secrets.BACKEND_FLY_APP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy Frontend to Fly.io
        working-directory: frontend
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy --app "$FRONTEND_FLY_APP" --dockerfile Dockerfile --remote-only --config fly.toml

      - name: Deploy Backend to Fly.io
        working-directory: backend
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy --app "$BACKEND_FLY_APP" --dockerfile Dockerfile --remote-only --config fly.toml
